name: APOCRPG
main: com.APOCRPG.Main.Plugin
version: 0
authors: [WIX0A,unarmed1618,Keeeenion]
description: Plugin
depend: [Vault]

commands:
    apocrpg:
        description: Main command
        aliases: [rpg]
        usage: /apocrpg, /rpg